-- 初始化权限 --

-- 系统管理 --
DELETE FROM SYS_FUNCTION;

INSERT INTO SYS_FUNCTION (ID,NAME,CODE,ACTION,ICON_CLASS,LINK_TARGET,SORT,TYPE,PARENT_ID,REMARK,STATUS,CREATE_TIME,CREATE_USER)
VALUES (10,'系统管理','manager:*','','fa fa-tv','1',10,1,NULL,'系统管理一级菜单',1,now(),'ADMIN');

INSERT INTO SYS_FUNCTION (ID,NAME,CODE,ACTION,ICON_CLASS,LINK_TARGET,SORT,TYPE,PARENT_ID,REMARK,STATUS,CREATE_TIME,CREATE_USER)
VALUES (11,'用户管理','manager:user','/manager/user/toUserInfo.do','fa fa-user','1',1,1,10,'系统管理-用户管理',1,now(),'ADMIN');

INSERT INTO SYS_FUNCTION (ID,NAME,CODE,ACTION,ICON_CLASS,LINK_TARGET,SORT,TYPE,PARENT_ID,REMARK,STATUS,CREATE_TIME,CREATE_USER)
VALUES (21,'用户管理-查询','user:query','/manager/user/queryUserInfo.do',NULL,'1',1,2,11,'用户管理-查询',1,now(),'ADMIN');

INSERT INTO SYS_FUNCTION (ID,NAME,CODE,ACTION,ICON_CLASS,LINK_TARGET,SORT,TYPE,PARENT_ID,REMARK,STATUS,CREATE_TIME,CREATE_USER)
VALUES (22,'用户管理-返回','user:back','/manager/user/goBackUser.do',NULL,'1',2,2,11,'用户管理-返回',1,now(),'ADMIN');

INSERT INTO SYS_FUNCTION (ID,NAME,CODE,ACTION,ICON_CLASS,LINK_TARGET,SORT,TYPE,PARENT_ID,REMARK,STATUS,CREATE_TIME,CREATE_USER)
VALUES (23,'用户管理-修改/添加','user:operation','/manager/user/operation.do',NULL,'1',3,2,11,'用户管理-修改/添加',1,now(),'ADMIN');

INSERT INTO SYS_FUNCTION (ID,NAME,CODE,ACTION,ICON_CLASS,LINK_TARGET,SORT,TYPE,PARENT_ID,REMARK,STATUS,CREATE_TIME,CREATE_USER)
VALUES (24,'用户管理-添加','user:add','/manager/user/addUserInfo.do',NULL,'1',4,2,11,'用户管理-添加',1,now(),'ADMIN');

INSERT INTO SYS_FUNCTION (ID,NAME,CODE,ACTION,ICON_CLASS,LINK_TARGET,SORT,TYPE,PARENT_ID,REMARK,STATUS,CREATE_TIME,CREATE_USER)
VALUES (25,'用户管理-修改','user:modify','/manager/user/modifyUserInfo.do',NULL,'1',5,2,11,'用户管理-修改',1,now(),'ADMIN');

INSERT INTO SYS_FUNCTION (ID,NAME,CODE,ACTION,ICON_CLASS,LINK_TARGET,SORT,TYPE,PARENT_ID,REMARK,STATUS,CREATE_TIME,CREATE_USER)
VALUES (26,'用户管理-删除','user:del','/manager/user/deleteUserInfo.do',NULL,'1',6,2,11,'用户管理-删除',1,now(),'ADMIN');

INSERT INTO SYS_FUNCTION (ID,NAME,CODE,ACTION,ICON_CLASS,LINK_TARGET,SORT,TYPE,PARENT_ID,REMARK,STATUS,CREATE_TIME,CREATE_USER)
VALUES (27,'用户管理-重复检查','user:dupCheck','/manager/user/userNameDuplicate.do',NULL,'1',7,2,11,'用户管理-重复检查',1,now(),'ADMIN');

INSERT INTO SYS_FUNCTION (ID,NAME,CODE,ACTION,ICON_CLASS,LINK_TARGET,SORT,TYPE,PARENT_ID,REMARK,STATUS,CREATE_TIME,CREATE_USER)
VALUES (12,'角色管理','manager:role','/manager/role/toRole.do','fa fa-street-view','1',2,1,10,'系统管理-角色管理',1,now(),'ADMIN');

INSERT INTO SYS_FUNCTION (ID,NAME,CODE,ACTION,ICON_CLASS,LINK_TARGET,SORT,TYPE,PARENT_ID,REMARK,STATUS,CREATE_TIME,CREATE_USER)
VALUES (13,'功能管理','manager:func','/manager/func/toFunction.do','fa fa-cog','1',3,1,10,'系统管理-功能管理',1,now(),'ADMIN');

-- 示例 --
INSERT INTO SYS_FUNCTION (ID,NAME,CODE,ACTION,ICON_CLASS,LINK_TARGET,SORT,TYPE,PARENT_ID,REMARK,STATUS,CREATE_TIME,CREATE_USER)
VALUES (200,'示例','sample','','fa-gamepad','1',99,1,NULL,'示例一级菜单',1,now(),'ADMIN');

INSERT INTO SYS_FUNCTION (ID,NAME,CODE,ACTION,ICON_CLASS,LINK_TARGET,SORT,TYPE,PARENT_ID,REMARK,STATUS,CREATE_TIME,CREATE_USER)
VALUES (201,'示例-翻页','sample:paginate','/sample/paginate.do','fa-google-wallet','1',1,1,200,'示例-翻页',1,now(),'ADMIN');

INSERT INTO SYS_FUNCTION (ID,NAME,CODE,ACTION,ICON_CLASS,LINK_TARGET,SORT,TYPE,PARENT_ID,REMARK,STATUS,CREATE_TIME,CREATE_USER)
VALUES (202,'示例-Shiro','sample:shiro','/sample/shiro.do','fa-google-wallet','1',2,1,200,'示例-权限控制',1,now(),'ADMIN');




-- 角色 --
DELETE FROM SYS_ROLE;

INSERT INTO SYS_ROLE ( ID,NAME,CODE,STATUS,CREATE_TIME,CREATE_USER )
VALUES (1, '管理员', 'admin',1, now(), 'ADMIN');

INSERT INTO SYS_ROLE ( ID,NAME,CODE,STATUS,CREATE_TIME,CREATE_USER )
VALUES (2, '示例', 'sample',1, now(), 'ADMIN');

-- 角色权限 --
DELETE FROM SYS_ROLE_FUNC;

INSERT INTO SYS_ROLE_FUNC (ROLE_ID,FUNC_ID) VALUES (1,10);
INSERT INTO SYS_ROLE_FUNC (ROLE_ID,FUNC_ID) VALUES (1,11);
INSERT INTO SYS_ROLE_FUNC (ROLE_ID,FUNC_ID)
(SELECT 1,ID FROM SYS_FUNCTION WHERE CODE LIKE 'user:%');

INSERT INTO SYS_ROLE_FUNC (ROLE_ID,FUNC_ID) VALUES (1,12);
INSERT INTO SYS_ROLE_FUNC (ROLE_ID,FUNC_ID) VALUES (1,13);

INSERT INTO SYS_ROLE_FUNC (ROLE_ID,FUNC_ID) VALUES (2,100);
INSERT INTO SYS_ROLE_FUNC (ROLE_ID,FUNC_ID) VALUES (2,101);
INSERT INTO SYS_ROLE_FUNC (ROLE_ID,FUNC_ID) VALUES (2,102);


-- 用户 --
DELETE FROM SYS_USER;

INSERT INTO SYS_USER (ID,USER_NAME,PASSWORD,NAME,STATUS,CREATE_TIME,CREATE_USER)
VALUES (1,'admin','F60FE75AD46673101F14ACECB2FCC699','管理员',1,now(),'ADMIN');

-- 用户角色 --
DELETE FROM SYS_USER_ROLE;

INSERT INTO SYS_USER_ROLE (USER_ID,ROLE_ID) VALUES (1,1);
